import os
import smtplib
from email.message import EmailMessage
from dotenv import load_dotenv

load_dotenv()

SMTP_HOST = os.getenv("SMTP_HOST")
SMTP_PORT = int(os.getenv("SMTP_PORT", 587))
SMTP_USER = os.getenv("SMTP_USER")
SMTP_PASS = os.getenv("SMTP_PASS")
PMC_EMAIL = os.getenv("PMC_EMAIL")


def send_pothole_email(lat, lon, image_url, severity, description):

    msg = EmailMessage()
    msg["From"] = SMTP_USER
    msg["To"] = PMC_EMAIL
    msg["Subject"] = "🚨 Urgent: Dangerous Pothole Detected in Pune"

    msg.set_content(f"""
Respected Sir/Madam,

A pothole complaint has been reported.

📝 Description:
{description}

📍 Location:
https://maps.google.com/?q={lat},{lon}

⚠ Severity:
{severity}

🖼 Image Evidence:
{image_url if image_url else "None"}

This report was generated by RoadEye System.

Regards,
RoadEye Automated System
""")

    with smtplib.SMTP(SMTP_HOST, SMTP_PORT, timeout=30) as server:
        server.starttls()
        server.login(SMTP_USER, SMTP_PASS)
        server.send_message(msg)

    print("✅ EMAIL SENT")
