-- 1. Table for Visual Detections (Red Markers)
create table detections (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  latitude float not null,
  longitude float not null,
  image_url text not null,
  severity text default 'Medium',
  pc_node_id text
);

-- 2. Table for Road Telemetry (Roughness Logs)
create table road_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  latitude float not null,
  longitude float not null,
  roughness float not null,
  session_id text
);

-- 3. Security Policies (Allow Public Read)
alter table detections enable row level security;
alter table road_logs enable row level security;
create policy "Public Read Detections" on detections for select using (true);
create policy "Public Read Logs" on road_logs for select using (true);
create policy "Public Insert Logs" on road_logs for insert with check (true);

